# Generated by Django 5.1.7 on 2025-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, error_messages={'unique': 'Этот номер телефона уже зарегистрирован'}, max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
    ]
